export const attractionCategories = [
    'abandoned_railway_stations',
    'accomodations',
    'alpine_hut',
    'amphitheatres',
    'amusements',
    'apartments',
    'aquariums',
    'aquatic_protected_areas',
    'aqueducts',
    'archaeology',
    'architecture',
    'art_galleries',
    'automobile_museums',
    'bakeries',
    'bank',
    'banks',
    'bars',
    'baths_and_saunas',
    'battlefields',
    'beaches',
    'biergartens',
    'biographical_museums',
    'bridges',
    'buddhist_temples',
    'burial_places',
    'cafes',
    'campsites',
    'canals',
    'canyons',
    'castles',
    'cathedrals',
    'catholic_churches',
    'caves',
    'cemeteries',
    'churches',
    'cinemas',
    'climbing',
    'clock_towers',
    'concert_halls',
    'conveniences',
    'crater_lakes',
    'cultural',
    'dams',
    'defensive_walls',
    'destroyed_objects',
    'dive_spots',
    'diving',
    'dolmens',
    'eastern_orthodox_churches',
    'factories',
    'farms',
    'fashion_museums',
    'fast_food',
    'fish_stores',
    'foods',
    'footbridges',
    'fortifications',
    'fortified_towers',
    'fountains',
    'fuel',
    'gardens_and_parks',
    'geological_formations',
    'geysers',
    'guest_houses',
    'high_islands',
    'hillforts',
    'hindu_temples',
    'historic',
    'historic_architecture',
    'historic_districts',
    'historic_house_museums',
    'historic_object',
    'historic_settlements',
    'historical_places',
    'history_museums',
    'hostels',
    'hot_springs',
    'industrial_facilities',
    'inland_islands',
    'installation',
    'interesting_places',
    'islands',
    'lagoons',
    'lighthouses',
    'local_museums',
    'malls',
    'manor_houses',
    'maritime_museums',
    'marketplaces',
    'mausoleums',
    'megaliths',
    'menhirs',
    'military_museums',
    'mills',
    'minarets',
    'mineshafts',
    'monasteries',
    'monuments',
    'monuments_and_memorials',
    'mosques',
    'mountain_peaks',
    'moveable_bridges',
    'museums',
    'museums_of_science_and_technology',
    'music_venues',
    'national_museums',
    'national_parks',
    'natural',
    'natural_monuments',
    'natural_springs',
    'nature_reserves',
    'nature_reserves_others',
    'necropolises',
    'observation_towers',
    'open_air_museums',
    'opera_houses',
    'other',
    'other_archaeological_sites',
    'other_beaches',
    'other_bridges',
    'other_buildings',
    'other_buildings_and_structures',
    'other_burial_places',
    'other_churches',
    'other_fortifications',
    'other_hotels',
    'other_islands',
    'other_lakes',
    'other_museums',
    'other_nature_conservation_areas',
    'other_technology_museums',
    'other_temples',
    'other_theatres',
    'other_towers',
    'other_winter_sports',
    'palaces',
    'planetariums',
    'power_stations',
    'pubs',
    'pyramids',
    'railway_museums',
    'railway_stations',
    'religion',
    'reservoirs',
    'restaurants',
    'rivers',
    'rock_formations',
    'roman_villas',
    'rune_stones',
    'saunas',
    'science_museums',
    'sculptures',
    'settlements',
    'shops',
    'sport',
    'springs_others',
    'squares',
    'stadiums',
    'suspension_bridges',
    'synagogues',
    'theatres_and_entertainments',
    'tourist_facilities',
    'tourist_object',
    'towers',
    'transmitter_towers',
    'transport',
    'triumphal_archs',
    'tumuluses',
    'unclassified_objects',
    'urban_environment',
    'viaducts',
    'view_points',
    'villas_and_chalet',
    'volcanoes',
    'wall_painting',
    'war_memorials',
    'watchtowers',
    'water',
    'water_towers',
    'waterfalls',
    'wildlife_reserves',
    'wineries',
    'winter_sports',
    'wrecks',
    'zoos'
];

/*
export const attractionCategories = [
    'Beach areas',
    'Natural areas',
    'Towns and cities',
    'Winter sport areas',
    'Areas known for culture and heritage',
    'Others'
];
*/

export const countries = [
    'Australia', 
    'Bangladesh', 
    'Bhutan', 
    'Canada', 
    'China',
    'India', 
    'Ireland', 
    'Myanmar (Burma)', 
    'New Zealand', 
    'Thailand', 
    'UK', 
    'USA', 
    'Vietnam'
]

/*
export const mainCty = [
    "Algeria",
    "Argentina",
    "Australia",
    "Brazil",
    "Canada",
    "China",
    "India",
    "Kazakhstan",
    "Russia",
    "United States",
    "Others"
];

export const countries = [
    "Afghanistan", 
    "Albania", 
    "Algeria", 
    "Andorra", 
    "Angola", 
    "Antigua and Barbuda", 
    "Argentina", 
    "Armenia", 
    "Australia", 
    "Austria", 
    "Azerbaijan",
    "The Bahamas", 
    "Bahrain", 
    "Bangladesh", 
    "Barbados", 
    "Belarus", 
    "Belgium", 
    "Belize", 
    "Benin", 
    "Bhutan", 
    "Bolivia", 
    "Bosnia and Herzegovina", 
    "Botswana", 
    "Brazil", 
    "Brunei", 
    "Bulgaria", 
    "Burkina", 
    "Faso", 
    "Burundi",
    "Cabo Verde", 
    "Cambodia", 
    "Cameroon", 
    "Canada", 
    "Central African Republic", 
    "Chad", 
    "Chile", 
    "China", 
    "Colombia", 
    "Comoros", 
    "Congo, Democratic Republic of the", 
    "Congo, Republic of the", 
    "Costa Rica", 
    "Côte d'Ivoire", 
    "Croatia", 
    "Cuba", 
    "Cyprus", 
    "Czech Republic", 
    "Denmark", 
    "Djibouti", 
    "Dominica", 
    "Dominican Republic", 
    "East Timor (Timor-Leste)", 
    "Ecuador", 
    "Egypt", 
    "El Salvador", 
    "Equatorial Guinea", 
    "Eritrea", 
    "Estonia", 
    "Eswatini", 
    "Ethiopia", 
    "Fiji", 
    "Finland", 
    "France", 
    "Gabon", 
    "The Gambia", 
    "Georgia", 
    "Germany", 
    "Ghana", 
    "Greece", 
    "Grenada", 
    "Guatemala", 
    "Guinea", 
    "Guinea-Bissau", 
    "Guyana", 
    "Haiti", 
    "Honduras", 
    "Hungary", 
    "Iceland", 
    "India", 
    "Indonesia", 
    "Iran", 
    "Iraq", 
    "Ireland", 
    "Israel", 
    "Italy", 
    "Jamaica", 
    "Japan", 
    "Jordan", 
    "Kazakhstan", 
    "Kenya", 
    "Kiribati", 
    "Korea, North", 
    "Korea, South", 
    "Kosovo", 
    "Kuwait", 
    "Kyrgyzstan", 
    "Laos", 
    "Latvia", 
    "Lebanon", 
    "Lesotho", 
    "Liberia", 
    "Libya", 
    "Liechtenstein", 
    "Lithuania", 
    "Luxembourg", 
    "Madagascar", 
    "Malawi", 
    "Malaysia", 
    "Maldives", 
    "Mali", 
    "Malta", 
    "Marshall Islands", 
    "Mauritania", 
    "Mauritius", 
    "Mexico", 
    "Micronesia, Federated States of", 
    "Moldova", 
    "Monaco", 
    "Mongolia", 
    "Montenegro", 
    "Morocco", 
    "Mozambique", 
    "Myanmar (Burma)", 
    "Namibia", 
    "Nauru", 
    "Nepal", 
    "Netherlands", 
    "New Zealand", 
    "Nicaragua", 
    "Niger", 
    "Nigeria", 
    "North Macedonia", 
    "Norway", 
    "Oman",
    "Pakistan", 
    "Palau", 
    "Panama", 
    "Papua New Guinea", 
    "Paraguay", 
    "Peru", 
    "Philippines", 
    "Poland", 
    "Portugal", 
    "Qatar",
    "Romania", 
    "Russia", 
    "Rwanda", 
    "Saint Kitts and Nevis", 
    "Saint Lucia", 
    "Saint Vincent and the Grenadines", 
    "Samoa", 
    "San Marino", 
    "Sao Tome and Principe", 
    "Saudi Arabia", 
    "Senegal", 
    "Serbia", 
    "Seychelles", 
    "Sierra Leone", 
    "Singapore", 
    "Slovakia", 
    "Slovenia", 
    "Solomon Islands", 
    "Somalia", 
    "South Africa", 
    "Spain", 
    "Sri Lanka", 
    "Sudan", 
    "Sudan, South", 
    "Suriname", 
    "Sweden", 
    "Switzerland", 
    "Syria", 
    "Taiwan", 
    "Tajikistan", 
    "Tanzania", 
    "Thailand", 
    "Togo", 
    "Tonga", 
    "Trinidad and Tobago", 
    "Tunisia", 
    "Turkey", 
    "Turkmenistan", 
    "Tuvalu", 
    "Uganda", 
    "Ukraine", 
    "United Arab Emirates", 
    "United Kingdom", 
    "United States", 
    "Uruguay", 
    "Uzbekistan",
    "Vanuatu", 
    "Vatican City", 
    "Venezuela", 
    "Vietnam", 
    "Yemen",
    "Zambia", 
    "Zimbabwe"
];
*/